export default {
  name: 'Pirate Percy',
  level: 3,
  initHp: 4000,
  hp: 4000,
  initPower: 50,
  power: 50,
  initArmor: 0,
  armor: 0,
  mana: 0,
  maxMana: 10,
  manaRegen: 1,
  armorRegen: 0,
  isCasting: false,
  bossTarget: null,
  description: `Yarrrrr`,
  weaponRewards: ['Decaying Blade'],
  goldReward: 1000,
  expReward: 1600,
  weaponChance: 1,
  progress_required: 0,
  icon: 'ra-pirate-captain',
  stage: 'stageOne',
  spells: [
    {
      name: 'Dynamite!',
      cost: 10,
      cast: 3,
      isChanneled: true,
      ticks: 2,
      coolDown: 0,
      powerRatio: 1,
      type: 'damage',
      description: "Apply a bomb effect to a random Recruit (that hasn't been bombed already) 2 times during the cast. Bombs will explode after 7 seconds, damaging ALL Recruits for (20%) of their Max Health",
      icon: 'ra-dynamite'
    },
    {
      name: 'Hook Hand!',
      cost: 0,
      cast: 2,
      coolDown: 5,
      powerRatio: 2,
      type: 'damage',
      singleTarget: false,
      onCooldown: false,
      manaLost: -5,
      description: "Damage the Boss' Target for (200%) of Boss Damage. Remove 5 Mana from the Player.",
      icon: 'ra-pirate-hook'
    },
    {
      name: 'Call Polly!',
      cost: 0,
      cast: 3,
      coolDown: 0,
      powerRatio: 0.5,
      percentage: 0.5,
      tickPower: 0,
      stunDuration: 5,
      type: 'damage',
      singleTarget: true,
      isChanneled: true,
      ticks: 10,
      tickPower: 0.05,
      onCooldown: false,
      description: "Damage a random enemy Recruit for (100%) Boss Power and stun them for 5 seconds.",
      icon: 'ra-parrot-head'
    }
  ],
  stageTwo: {
    stage: 'stageTwo',
    description: 'During Stage 2 the Core will have 50 Power and gain 1 Mana per Second',
    manaRegen: 1,
    power: 50,
    spells: [
      {
        name: 'Meltdown',
        manaRequired: 50,
        cast: 10,
        cost: 0,
        coolDown: 0,
        onCooldown: false,
        singleTarget: false,
        powerRatio: 1,
        stage: 'stageThree',
        description: '(Only useable at 50 Mana) Change to Stage 3, gaining 50 Power and Poisoning ALL Recruits for (60%) of their Max Health over 15 seconds',
        icon: 'ra-radioactive'
      },
      {
        name: 'Half Life',
        cast: 5,
        cost: 0,
        coolDown: 10,
        type: 'damage',
        powerRatio: 1,
        onCooldown: false,
        singleTarget: false,
        description: "Damage EACH Recruit for (50%) of their CURRENT Health",
        icon: 'ra-split-body'
      },
      {
        name: 'Magma Surge',
        cost: 0,
        cast: 5,
        coolDown: 0,
        powerRatio: 0.5,
        percentage: 0.5,
        tickPower: 0,
        type: 'damage',
        singleTarget: true,
        isChanneled: true,
        ticks: 10,
        tickPower: 0.05,
        onCooldown: false,
        description: "Damage ALL enemies for (50%) of PlAYER Power during the cast, and then Damage the Target for (50%) Boss Power",
        icon: 'ra-flamed-leaf'
      }
    ]
  },
  stageThree: {
    stage: 'stageThree',
    description: 'During Stage 3 the Core will gain 1 Mana per second, increasing in Damage as the Mana reduces. Once at 100 Mana the Core will explode, killing the Player and their Recruits',
    manaRegen: 1,
    power: 100,
    spells: [
      {
        name: 'Explode',
        cast: 10,
        cost: 0,
        coolDown: 0,
        type: 'support',
        manaRequired: 100,
        powerRatio: 10000,
        onCooldown: false,
        singleTarget: false,
        description: "(Only Useable at 100 Mana): Damage ALL enemy characters for (1,000,000%) Boss Power",
        icon: 'ra-crowned-explosion'
      },
      {
        name: 'Radiate',
        cast: 5,
        cost: 0,
        coolDown: 10,
        type: 'damage',
        powerRatio: 1,
        isChanneled: true,
        ticks: 5,
        tickPercentage: 0.08,
        onCooldown: false,
        singleTarget: true,
        description: "Poison ALL Recruits for (60%) of their Max Health over 15 seconds. The Poison increases in damage by 1% for every 1 Mana the Boss has.",
        icon: 'ra-sun-radiations'
      },
      {
        name: 'Half Life',
        cast: 5,
        cost: 0,
        coolDown: 10,
        type: 'damage',
        powerRatio: 1,
        onCooldown: false,
        singleTarget: false,
        description: "Damage EACH Recruit for (50%) of their CURRENT Health",
        icon: 'ra-split-body'
      },
      {
        name: 'Fission',
        cast: 5,
        cost: 0,
        coolDown: 0,
        onCooldown: false,
        singleTarget: true,
        powerRatio: 1,
        power: -10,
        description: 'Damage the Boss Target for (100%) Boss Power, lose 10 Power',
        icon: 'ra-explosive-meeting'
      }
    ]
  }
}
