export default {
  name: 'Pirate Percy',
  level: 3,
  initHp: 4000,
  hp: 4000,
  initPower: 50,
  power: 50,
  initArmor: 0,
  armor: 0,
  mana: 0,
  maxMana: 10,
  manaRegen: 1,
  armorRegen: 0,
  isCasting: false,
  bossTarget: null,
  description: `Yarrrrr`,
  weaponRewards: ['Decaying Blade'],
  goldReward: 1000,
  expReward: 1600,
  weaponChance: 1,
  progress_required: 0,
  icon: 'ra-pirate-captain',
  stage: 'stageOne',
  stageOne: {
    stage: 'stageOne',
    manaRegen: 1,
    power: 50,
    mana: 0,
    maxMana: 10,
    armor: 0,
    initArmor: 0,
    spells: [
    {
      name: 'Board Ship!',
      cost: 0,
      cast: 3,
      coolDown: 10,
      description: 'Change to stage 2. Only usable at 2/3 of full health. During stage 2 the Boss will have 2000 armor , 100 mana and a new set of abilties.',
      icon: 'ra-galleon',
      stage: 'stageTwo',
      percentage: 2/3

    },
    {
      name: 'Dynamite!',
      cost: 10,
      cast: 3,
      isChanneled: true,
      ticks: 2,
      coolDown: 0,
      powerRatio: 1,
      type: 'damage',
      description: "Apply a bomb effect to a random Recruit (that hasn't been bombed already) 2 times during the cast. Bombs will explode after 7 seconds, damaging ALL Recruits for (20%) of their Max Health",
      icon: 'ra-dynamite'
    },
    {
      name: 'Hook Hand!',
      cost: 0,
      cast: 2,
      coolDown: 5,
      powerRatio: 2,
      type: 'damage',
      singleTarget: false,
      onCooldown: false,
      manaLost: -5,
      description: "Damage the Boss' Target for (200%) of Boss Damage. Remove 5 Mana from the Player.",
      icon: 'ra-pirate-hook'
    },
    {
      name: 'Call Polly!',
      cost: 0,
      cast: 3,
      coolDown: 0,
      powerRatio: 0.5,
      percentage: 0.5,
      tickPower: 0,
      stunDuration: 5,
      type: 'damage',
      singleTarget: true,
      isChanneled: true,
      ticks: 10,
      tickPower: 0.05,
      onCooldown: false,
      description: "Damage a random enemy Recruit for (100%) Boss Power and stun them for 5 seconds.",
      icon: 'ra-parrot-head'
    }
    ]
  },
  spells: [
    {
      name: 'Board Ship!',
      cost: 0,
      cast: 3,
      coolDown: 10,
      description: 'Change to stage 2. Only usable at 2/3 of full health, and again at 1/3. During stage 2 the Boss will have 2000 armor , 100 mana and a new set of abilties.',
      icon: 'ra-galleon',
      stage: 'stageOne',
      percentage: 2/3
    },
    {
      name: 'Dynamite!',
      cost: 10,
      cast: 3,
      isChanneled: true,
      ticks: 2,
      coolDown: 0,
      powerRatio: 1,
      type: 'damage',
      description: "Apply a bomb effect to a random Recruit (that hasn't been bombed already) 2 times during the cast. Bombs will explode after 7 seconds, damaging ALL Recruits for (20%) of their Max Health",
      icon: 'ra-dynamite'
    },
    {
      name: 'Hook Hand!',
      cost: 0,
      cast: 2,
      coolDown: 5,
      powerRatio: 2,
      type: 'damage',
      singleTarget: false,
      onCooldown: false,
      manaLost: -5,
      description: "Damage the Boss' Target for (200%) of Boss Damage. Remove 5 Mana from the Player.",
      icon: 'ra-pirate-hook'
    },
    {
      name: 'Call Polly!',
      cost: 0,
      cast: 3,
      coolDown: 0,
      powerRatio: 0.5,
      percentage: 0.5,
      tickPower: 0,
      stunDuration: 5,
      type: 'damage',
      singleTarget: true,
      isChanneled: true,
      ticks: 10,
      tickPower: 0.05,
      onCooldown: false,
      description: "Damage a random enemy Recruit for (100%) Boss Power and stun them for 5 seconds.",
      icon: 'ra-parrot-head'
    }
  ],
  stageTwo: {
    stage: 'stageTwo',
    description: 'The Boss will start stage 2 with 2000 Armor and 100 mana. The boss will not generate mana during this stage',
    manaRegen: 0,
    power: 50,
    armor: 2000,
    initArmor: 2000,
    mana: 100,
    maxMana: 100,
    spells: [
      {
        name: 'Jump Ship!',
        cast: 3,
        cost: 0,
        coolDown: 60,
        description: '(Used at 0 Armor) Return to Stage 1, losing all armor and setting Max Mana to 10.',
        icon: 'ra-shipwreck',
        stage: 'stageOne'
      },
      {
        name: 'Harpoon!',
        cast: 3,
        cost: 0,
        coolDown: 10,
        onCooldown: false,
        singleTarget: true,
        powerRatio: 2,
        stunDuration: 3,
        stage: 'stageTwo',
        description: 'Damage the Boss target for (200%) of Boss Power and stun them, and any adjacent Recruits, for 3 seconds.',
        icon: 'ra-harpoon-chain'
      },
      {
        name: 'Rapid Fire!',
        cast: 5,
        cost: 10,
        coolDown: 1,
        type: 'damage',
        powerRatio: 0.5,
        percentage: 0.1,
        onCooldown: false,
        singleTarget: false,
        isChanneled: true,
        ticks: 10,
        description: "Damage a random Recruit for (10%) of their Health. Occurs 10 times during the cast of the spell. Each shot will damage the Player for (50%) of Boss Power if all Recruits are dead.",
        icon: 'ra-split-body'
      },
      {
        name: 'Dynamite!',
        cost: 10,
        cast: 3,
        isChanneled: true,
        ticks: 2,
        coolDown: 0,
        powerRatio: 1,
        type: 'damage',
        description: "Apply a bomb effect to a random Recruit (that hasn't been bombed already) 2 times during the cast. Bombs will explode after 7 seconds, damaging ALL Recruits for (20%) of their Max Health",
        icon: 'ra-dynamite'
      },
    ]
  },
  stageThree: {
    stage: 'stageThree',
    description: 'During Stage 3 the Core will gain 1 Mana per second, increasing in Damage as the Mana reduces. Once at 100 Mana the Core will explode, killing the Player and their Recruits',
    manaRegen: 1,
    power: 100,
    spells: [
      {
        name: 'Explode',
        cast: 10,
        cost: 0,
        coolDown: 0,
        type: 'support',
        manaRequired: 100,
        powerRatio: 10000,
        onCooldown: false,
        singleTarget: false,
        description: "(Only Useable at 100 Mana): Damage ALL enemy characters for (1,000,000%) Boss Power",
        icon: 'ra-crowned-explosion'
      },
      {
        name: 'Radiate',
        cast: 5,
        cost: 0,
        coolDown: 10,
        type: 'damage',
        powerRatio: 1,
        isChanneled: true,
        ticks: 5,
        tickPercentage: 0.08,
        onCooldown: false,
        singleTarget: true,
        description: "Poison ALL Recruits for (60%) of their Max Health over 15 seconds. The Poison increases in damage by 1% for every 1 Mana the Boss has.",
        icon: 'ra-sun-radiations'
      },
      {
        name: 'Half Life',
        cast: 5,
        cost: 0,
        coolDown: 10,
        type: 'damage',
        powerRatio: 1,
        onCooldown: false,
        singleTarget: false,
        description: "Damage EACH Recruit for (50%) of their CURRENT Health",
        icon: 'ra-split-body'
      },
      {
        name: 'Fission',
        cast: 5,
        cost: 0,
        coolDown: 0,
        onCooldown: false,
        singleTarget: true,
        powerRatio: 1,
        power: -10,
        description: 'Damage the Boss Target for (100%) Boss Power, lose 10 Power',
        icon: 'ra-explosive-meeting'
      }
    ]
  }
}
