export default {
  name: 'Biting Bear',
  level: 1,
  initHp: 500,
  hp: 500,
  initPower: 20,
  power: 20,
  initArmor: 200,
  armor: 200,
  mana: 25,
  maxMana: 25,
  manaRegen: 1,
  armorRegen: 0,
  isCasting: false,
  bossTarget: null,
  description: "You encounter a starving Bear in The Wilds, and this Bear is very, very hungry...",
  weaponRewards: ['Bear Fangs', 'Bear Heart', 'Bear Claw Arrows', 'Chew Toy'],
  goldReward: 300,
  expReward: 350,
  weaponChance: 1,
  progress_required: 1,
  icon: 'ra-bear-head',
  spells: [
    {
      name: 'Swipe',
      cast: 3,
      cost: 10,
      coolDown: 10,
      type: 'damage',
      singleTarget: false,
      powerRatio: 1,
      onCooldown: false,
      description: 'Damage ALL enemy characters for 100% BOSS POWER',
      icon: 'ra-claw-slashes'
    },
    {
      name: 'Protect',
      cast: 3,
      cost: 5,
      coolDown: 10,
      type: 'armor',
      singleTarget: false,
      powerRatio: 25,
      onCooldown: false,
      description: 'Gain 25 ARMOR',
      icon: 'ra-energy-shield'
    },
    {
      name: 'Bite',
      cast: 5,
      cost: 0,
      coolDown: 1,
      powerRatio: 2,
      stunDuration: 3,
      type: 'damage',
      singleTarget: true,
      onCooldown: false,
      description: "Damage the Boss' TARGET for 200% of BOSS POWER. Also Stuns the Target for 3 seconds. (Stunned Recruits cannot Attack)",
      icon: 'ra-fangs'
    }
  ]
}
