export default {
  name: 'Biting Bear',
  level: 1,
  initHp: 500,
  hp: 500,
  initPower: 60,
  power: 60,
  initArmor: 200,
  armor: 200,
  mana: 5,
  maxMana: 5,
  manaRegen: 5,
  armorRegen: 0,
  isCasting: false,
  bossTarget: null,
  description: "You encounter a starving Bear in The Wilds, and this Bear is very, very hungry...",
  weaponRewards: ['Bear Fangs', 'Bear Heart'],
  goldReward: 200,
  weaponChance: 1,
  progress_required: 0,
  spells: [
    {
      name: 'Swipe',
      cast: 5,
      cost: 2,
      coolDown: 5,
      type: 'damage',
      singleTarget: false,
      powerRatio: 1,
      onCooldown: false,
      description: 'Damage ALL enemy characters for 100% BOSS POWER',
    },
    {
      name: 'Protect',
      cast: 0.5,
      cost: 3,
      coolDown: 5,
      type: 'armor',
      singleTarget: false,
      powerRatio: 50,
      onCooldown: false,
      description: 'Gain 50 ARMOR'
    },
    {
      name: 'Bite',
      cost: 0,
      cast: 5,
      coolDown: 1,
      powerRatio: 2,
      type: 'damage',
      singleTarget: true,
      onCooldown: false,
      description: "Damage the Boss' TARGET for 200% of BOSS POWER"
    }
  ]
}
