export default {
  name: 'Spitting Spider',
  level: 1,
  initHp: 1000,
  hp: 1000,
  initPower: 20,
  power: 20,
  initArmor: 100,
  armor: 100,
  mana: 0,
  maxMana: 10,
  manaRegen: 1,
  armorRegen: 0,
  isCasting: false,
  bossTarget: null,
  description: "This Spider knows you hate her, but she hates you too, and she spits on you for it.",
  goldReward: 400,
  weaponRewards: ['Fine Silk', 'Spider Eye Wand'],
  weaponChance: 1,
  progress_required: 2,
  icon: 'ra-spider-face',
  spells: [
    {
      name: 'Feed',
      cast: 5,
      cost: 10,
      coolDown: 10,
      type: 'special',
      singleTarget: false,
      powerRatio: 5,
      onCooldown: false,
      description: "Gain +5 POWER"
    },
    {
      name: 'Swipe',
      cast: 4,
      cost: 0,
      coolDown: 3,
      type: 'damage',
      singleTarget: false,
      powerRatio: 1,
      onCooldown: false,
      description: "Damage ALL enemy characters for 100% BOSS POWER",
      icon: 'ra-bird-claw'
    },
    {
      name: 'Spit',
      cast: 3,
      cost: 0,
      coolDown: 3,
      type: 'damage',
      singleTarget: false,
      powerRatio: 1,
      onCooldown: false,
      description: "Damage the PLAYER for 100% BOSS POWER",
      icon: 'ra-player-thunder-struck'
    },
  ]
}
