module.exports = {
  ['Training Staff']: (level, id) => ({
    name: 'Training Staff',
    type: 'Weapon',
    level,
    id,
    hp: 1000,
    power: 20,
    mana: 100,
    manaRegen: 1,
    class: 'Player',
    description: 'It comes with a note attached; "Hitting your Recruits with this will NOT heal them!"',
    bonusEffect: null,
    icon: 'ra-crystal-wand'
  }),
  ['Cursed Staff of the Wilds']: (level, id) => ({
    name: 'Cursed Staff of the Wilds',
    type: 'Weapon',
    level,
    id,
    hp: 1200,
    power: 30,
    mana: 120,
    manaRegen: 1,
    class: 'Player',
    description: 'This Staff is covered in thorns. You hear the sounds of a Bear Wailing from inside of it.',
    bonusEffect: null,
    icon: 'ra-pine-tree'
  }),
  ['Cleansed Staff of the Wilds']: (level, id) => ({
    name: 'Cleansed Staff of the Wilds',
    type: 'Weapon',
    level,
    id,
    hp: 1200,
    power: 30,
    mana: 60,
    manaRegen: 2,
    class: 'Player',
    description: 'You have lifted the curse upon the Wilds, and the Wilds presents you this as a reward.',
    bonusEffect: null,
    icon: 'ra-pine-tree'
  }),
  ['Plagued Staff of the Swamp']: (level, id) => ({
    name: 'Plagued Staff of the Swamp',
    type: 'Weapon',
    level,
    id,
    hp: 1000,
    power: 40,
    mana: 200,
    manaRegen: 0,
    class: 'Player',
    description: 'The staff resonates great power, but something about it feels so wrong.',
    bonusEffect: 'Poison',
    effectDescription: `Your targeted heals Poison the target for 20% of target's hp as damage every 5 seconds for 15 seconds`,
    icon: 'ra-biohazard'
  }),
  ['Cleansed Staff of the Woods']: (level, id) => ({
    name: 'Cleansed Staff of the Woods',
    type: 'Weapon',
    level,
    id,
    hp: 1500,
    power: 35,
    mana: 100,
    manaRegen: 2,
    class: 'Player',
    description: 'Made from a powerful Oak Tree. A small artifact of purity from the Woods that used to be...',
    bonusEffect: 'curePoison',
    effectDescription: "Your targeted heals remove any Poison effect from the target",
    icon: 'ra-sprout'
  }),
  ['Dragon Scale']: (level, id) => ({
    name: 'Dragon Scale',
    type: 'Weapon',
    level,
    id,
    hp: 0.2,
    power: -0.5,
    speed: 2,
    class: 'Paladin',
    description: 'A Scale from a Dragon, this should make a good shield',
    bonusEffect: null,
    icon: 'ra-cracked-shield'
  }),
  ['Bear Fangs']: (level, id) => ({
    name: 'Bear Fangs',
    type: 'Weapon',
    level,
    id,
    hp: -0.1,
    power: 0.5,
    speed: -1,
    class: 'Rogue',
    description: 'A set of Bear Fangs. Good for stabbing, not very good for blocking',
    bonusEffect: null,
    icon: 'ra-alligator-clip'
  }),
  ['Bear Heart']: (level, id) => ({
    name: 'Bear Heart',
    type: 'Weapon',
    level,
    id,
    hp: 0.5,
    power: 0,
    speed: -1,
    class: 'Warlock',
    description: 'The heart still beats, only a true sadist would find this useful',
    bonusEffect: null,
    icon: 'ra-bleeding-hearts'
  }),
  ['Bear Claw Arrows']: (level, id) => ({
    name: 'Bear Claw Arrows',
    type: 'Weapon',
    level,
    id,
    hp: 0.1,
    power: 0.33,
    speed: -1,
    class: 'Hunter',
    description: "There are Ten arrows, but they seem sturdy enough to reuse.",
    bonusEffect: null,
    icon: 'ra-arrow-cluster'
  }),
  ['Massive Shell']: (level, id) => ({
    name: 'Massive Shell',
    type: 'Weapon',
    level,
    id,
    hp: 0.6,
    power: -0.3,
    speed: 0,
    class: 'Warrior',
    description: 'A shell so heavy only a Warrior can weild it, not good for hitting things with, but great for not dying!',
    bonusEffect: 'taunt',
    effectDescription: "The Warrior's Attacks now force the Boss to target the Warrior",
    icon: 'ra-spiral-shell'
  }),
  ['Ancient Pearls']: (level, id) => ({
    name: 'Ancient Pearls',
    type: 'Weapon',
    level,
    id,
    hp: -0.4,
    power: 0.2,
    speed: 1,
    class: 'Monk',
    description: "Strange, the Turtle was growing Pearls under it's shell",
    bonusEffect: null,
    icon: 'ra-gem'
  }),
  ['Glowing Pearl Talisman']: (level, id) => ({
    name: 'Glowing Pearl Talisman',
    type: 'Weapon',
    level,
    id,
    hp: 0,
    power: -0.5,
    speed: 1,
    class: 'Shaman',
    description: "Strange, the Turtle was growing Pearls under it's shell",
    bonusEffect: null,
    icon: 'ra-ball'
  }),
  ['Fine Silk']: (level, id) => ({
    name: 'Fine Silk',
    type: 'Weapon',
    level,
    id,
    hp: -0.3,
    power: 0.2,
    speed: 1,
    class: 'Priest',
    description: "The Spider had spun some amazing silk. Very light, with",
    bonusEffect: null,
    icon: 'ra-incense'

  }),
  ['Spider Eye Wand']: (level, id) => ({
    name: 'Spider Eye Wand',
    type: 'Weapon',
    level,
    id,
    hp: 0.4,
    power: 0.3,
    speed: -1,
    class: 'Mage',
    description: "It's a stick with a Spider Eye on the end, so obviously it's magical",
    bonusEffect: null,
    icon: 'ra-eyeball'
  }),
  ['Plagued Aegis']: (level, id) => ({
    name: 'Plagued Aegis',
    type: 'Weapon',
    level,
    id,
    hp: 0.3,
    power: 0,
    speed: 1,
    class: 'Paladin',
    description: 'A lost shield from a fallen adventurer. "A. Blaine" is engraved on the back',
    bonusEffect: 'selfPoison',
    effectDescription: `The character's attacks have a chance to Poison themselves for 60% of their Max Health over 15 seconds`,
    icon: 'ra-poison-cloud'
  }),
  ['Plagued Blade']: (level, id) => ({
    name: 'Plagued Blade',
    type: 'Weapon',
    level,
    id,
    hp: -0.5,
    power: 0.5,
    speed: 1,
    class: 'Warrior',
    description: 'A lost weapon from a fallen adventurer. "A Blaine" is engraved on the back',
    bonusEffect: 'selfPoison',
    effectDescription: `The character's attacks have a chance to Poison themselves for 60% of their Max Health over 15 seconds`,
    icon: 'ra-poison-cloud'
  }),
  ['Plagued Daggers']: (level, id) => ({
    name: 'Plagued Daggers',
    type: 'Weapon',
    level,
    id,
    hp: 0.5,
    power: -0.5,
    speed: 2,
    class: 'Rogue',
    description: 'A lost pair of Daggers from a fallen adventurer. "Joe Van Boe" is engraved on the back',
    bonusEffect: 'selfPoison',
    effectDescription: `The character's attacks have a chance to Poison themselves for 60% of their Max Health over 15 seconds`,
    icon: 'ra-poison-cloud'
  }),
  ['Plagued Arrows']: (level, id) => ({
    name: 'Plagued Arrows',
    type: 'Weapon',
    level,
    id,
    hp: -0.3,
    power: -0.5,
    speed: 3,
    class: 'Hunter',
    description: 'A lost Quiver of Arrows from a fallen adventurer. "Joe Van Boe" is engraved on the back',
    bonusEffect: 'selfPoison',
    effectDescription: `The character's attacks have a chance to Poison themselves for 60% of their Max Health over 15 seconds`,
    icon: 'ra-chemical-arrow'
  }),
  ['Plagued Scythe']: (level, id) => ({
    name: 'Plagued Scythe',
    type: 'Weapon',
    level,
    id,
    hp: -0.6,
    power: 0,
    speed: 2,
    class: 'Warlock',
    description: 'A lost weapon from a fallen adventurer. "A A. Ron" is engraved on the back',
    bonusEffect: 'selfPoison',
    effectDescription: `The character's attacks have a chance to Poison themselves for 60% of their Max Health over 15 seconds`,
    icon: 'ra-poison-cloud'
  }),
  ['Plagued Stave']: (level, id) => ({
    name: 'Plagued Stave',
    type: 'Weapon',
    level,
    id,
    hp: -0.5,
    power: 0.5,
    speed: 0,
    class: 'Monk',
    description: 'A lost weapon from a fallen adventurer. "Dr. Dayne" is engraved on the back',
    bonusEffect: 'selfPoison',
    effectDescription: `The character's attacks have a chance to Poison themselves for 60% of their Max Health over 15 seconds`,
    icon: 'ra-poison-cloud'
  }),
  ['Plagued Wand']: (level, id) => ({
    name: 'Plagued Wand',
    type: 'Weapon',
    level,
    id,
    hp: 0.5,
    power: -0.3,
    speed: 1,
    class: 'Mage',
    description: 'A lost weapon from a fallen adventurer. "Jazz Man" is engraved on the back',
    bonusEffect: 'selfPoison',
    effectDescription: `The character's attacks have a chance to Poison themselves for 60% of their Max Health over 15 seconds`,
    icon: 'ra-poison-cloud'
  }),
  ['The Antidote']: (level, id) => ({
    name: 'The Antidote',
    type: 'Weapon',
    level,
    id,
    hp: 0.3,
    power: -1,
    speed: 2,
    class: 'Shaman',
    description: 'A lost weapon from a fallen adventurer. "L. N." is engraved on the back',
    bonusEffect: 'curePoison',
    effectDescription: `When the Shaman casts Renew on a target, the target is cured of any Poison Effect`,
    icon: 'ra-heart-bottle'
  }),
  ['Glowing Libram']: (level, id) => ({
    name: 'Glowing Libram',
    type: 'Weapon',
    level,
    id,
    hp: -0.3,
    power: 0,
    speed: 3,
    class: 'Priest',
    description: 'A lost weapon from a fallen adventurer. "L. N." is engraved on the back',
    bonusEffect: 'curePoison',
    effectDescription: `The Priest's heals cure any Poison effect on the spell's Target`,
    icon: 'ra-book'
  })
}
