export default {
  name: 'Lunging Locusts',
  level: 2,
  initHp: 200,
  hp: 200,
  initPower: 5,
  power: 5,
  initArmor: 0,
  armor: 0,
  mana: 0,
  maxMana: 100,
  manaRegen: 1,
  armorRegen: 0,
  isCasting: false,
  bossTarget: null,
  description: "As you explore deeper into the Swamp, you see less life around you, and a soft buzzing sound starts getting louder... and louder...",
  weaponRewards: [],
  goldReward: 100,
  weaponChance: 0.5,
  progress_required: 0,
  spells: [
    {
      name: 'Overwhelm',
      cast: 10,
      cost: 100,
      coolDown: 0,
      type: 'damage',
      singleTarget: false,
      powerRatio: 50,
      onCooldown: false,
      description: 'Damage ALL enemy characters for 5000% BOSS POWER',
    },
    {
      name: 'Regenerate',
      cast: 5,
      cost: 0,
      coolDown: 10,
      type: 'armor',
      singleTarget: false,
      powerRatio: 1,
      armor: 0,
      health: 10,
      onCooldown: false,
      description: 'Gain 10 Health'
    },
    {
      name: 'Lunge',
      cost: 0,
      cast: 3,
      coolDown: 3,
      powerRatio: 1,
      type: 'damage',
      singleTarget: true,
      onCooldown: false,
      description: "Damage a Random enemy party member for 100% Boss Power and add a Poison Effect to that target for 100% Boss Power as Damage every 5 seconds for 15 seconds"
    }
  ]
}
