export default {
  name: 'Lunging Locusts',
  level: 2,
  initHp: 2000,
  hp: 2000,
  initPower: 1000,
  power: 1000,
  initArmor: 0,
  armor: 0,
  mana: 0,
  maxMana: 120,
  manaRegen: 1,
  armorRegen: 0,
  isCasting: false,
  bossTarget: null,
  description: "As you explore deeper into the Swamp, you see less life around you, and a soft buzzing sound starts getting louder... and louder...",
  weaponRewards: ['Plagued Wand', 'Plagued Stave', 'Plagued Scythe'],
  goldReward: 500,
  weaponChance: 1,
  progress_required: 1,
  icon: ' ra-butterfly',
  spells: [
    {
      name: 'Overwhelm',
      cast: 20,
      cost: 120,
      coolDown: 0,
      type: 'damage',
      singleTarget: false,
      manaRequired: 120,
      powerRatio: 100,
      onCooldown: false,
      description: 'Damage ALL enemy characters for 10000% BOSS POWER',
      icon: 'ra-food-chain'
    },
    {
      name: 'Regenerate',
      cast: 3,
      cost: 0,
      coolDown: 20,
      type: 'armor',
      singleTarget: false,
      powerRatio: 1,
      armor: 0,
      health: 100,
      onCooldown: false,
      description: 'Gain 100 Health',
      icon: 'ra-regeneration'
    },
    {
      name: 'Lunge',
      cost: 0,
      cast: 4,
      coolDown: 0,
      powerRatio: 1,
      type: 'damage',
      singleTarget: true,
      onCooldown: false,
      percentage: 0.3,
      description: "Damage a random Recruit for (30%) of their Max Health and Poison that Recruit, dealing 60% of their Max Health over 15 seconds, Prioritises Non Poisoned Recruits.",
      icon: 'ra-overhead'
    }
  ]
}
