export default {
  name: 'Plague Piltherer',
  level: 2,
  initHp: 100,
  hp: 100,
  initPower: 0,
  power: 0,
  initArmor: 100,
  armor: 100,
  mana: 10,
  maxMana: 10,
  manaRegen: 1,
  armorRegen: 0,
  isCasting: false,
  bossTarget: null,
  description: "A crazed man darts around the Swamp lands, scavenging the many corpses for their precious loot. You even see him drinking some of that disgusting slime!",
  weaponRewards: [],
  goldReward: 100,
  weaponChance: 0.5,
  progress_required: 0,
  spells: [
    {
      name: 'Ingest Plague',
      cast: 10,
      cost: 10,
      coolDown: 10,
      type: 'damage',
      singleTarget: false,
      powerRatio: 0,
      power: 5,
      onCooldown: false,
      description: 'Gain 5 Power. (Only usable when at 0 Power)',
    },
    {
      name: 'Spread Plague',
      cost: 0,
      cast: 5,
      coolDown: 10,
      powerRatio: 1,
      type: 'damage',
      singleTarget: false,
      onCooldown: false,
      power: -1,
      description: "Poison All enemy party members for 100% Boss Power every 3 seconds for 15 seconds. Lose 1 Power. (Only useable at 5 Power)"
    },
    {
      name: 'Regenerate',
      cast: 3,
      cost: 3,
      coolDown: 10,
      type: 'armor',
      singleTarget: false,
      powerRatio: 1,
      armor: 10,
      health: 10,
      onCooldown: false,
      description: 'Gain 10 ARMOR and 10 Health'
    },
    {
      name: 'Ravage',
      cost: 0,
      cast: 3,
      coolDown: 0,
      powerRatio: 1,
      type: 'damage',
      singleTarget: false,
      onCooldown: false,
      power: -1,
      description: "Damage all enemy characters for 100% Boss Power, lose 1 Power if enemy party is still alive"
    }
  ]
}
