export default {
  name: 'Seeping Slime',
  level: 2,
  initHp: 100,
  hp: 100,
  initPower: 5,
  power: 5,
  initArmor: 10,
  armor: 10,
  mana: 10,
  maxMana: 30,
  manaRegen: 1,
  armorRegen: 0,
  isCasting: false,
  bossTarget: null,
  description: "As you investigate the off coloured swamp water at the entrance of the swamp, the water starts investigating you.",
  weaponRewards: [],
  goldReward: 250,
  weaponChance: 0.5,
  progress_required: 0,
  spells: [
    {
      name: 'Regenerate',
      cast: 10,
      cost: 30,
      coolDown: 30,
      type: 'damage',
      singleTarget: false,
      powerRatio: 1,
      armor: 10,
      health: 50,
      onCooldown: false,
      description: 'Gain 10 Armor. Restore 50 Health. (Only usable when on 0 Armor and below 50 Health)',
    },
    {
      name: 'Seep',
      cast: 3,
      cost: 3,
      coolDown: 5,
      type: 'damage',
      singleTarget: true,
      powerRatio: 1,
      onCooldown: false,
      description: 'Damage All enemy characters for 100% Boss Power. This spell also damages the caster for 100% Power'
    },
    {
      name: 'Poison',
      cost: 0,
      cast: 2,
      coolDown: 5,
      powerRatio: 1,
      type: 'damage',
      singleTarget: true,
      onCooldown: false,
      description: "Apply a Poison Effect to the Boss' Target, Dealing 100% Boss Power as Damage every 5 seconds for 15 seconds"
    }
  ]
}
