export default {
  name: 'Seeping Slime',
  level: 2,
  initHp: 1000,
  hp: 1000,
  initPower: 40,
  power: 40,
  initArmor: 500,
  armor: 500,
  mana: 0,
  maxMana: 30,
  manaRegen: 1,
  armorRegen: 0,
  isCasting: false,
  bossTarget: null,
  description: "As you investigate the off coloured swamp water at the entrance of the swamp, the water starts investigating you.",
  weaponRewards: ['Plagued Aegis', 'Plagued Daggers', 'Plagued Wand', 'Plagued Blade', 'Plagued Stave', 'Plagued Scythe', 'Glowing Libram', 'Plagued Staff of the Swamp'],
  goldReward: 400,
  weaponChance: 1,
  progress_required: 0,
  icon: 'ra-ocean-emblem',
  spells: [
    {
      name: 'Regenerate',
      cast: 5,
      cost: 20,
      coolDown: 20,
      type: 'damage',
      singleTarget: false,
      powerRatio: 1,
      armor: 0,
      health: 500,
      onCooldown: false,
      description: 'Restore 500 Health. (Only usable when below 500 Health)',
      icon: 'ra-regeneration'
    },
    {
      name: 'Seep',
      cast: 5,
      cost: 5,
      coolDown: 5,
      type: 'damage',
      singleTarget: true,
      powerRatio: 1,
      onCooldown: false,
      description: 'Damage All enemy characters for 100% Boss Power. This spell also damages the caster for 100% Power',
      icon: 'ra-bleeding-hearts'
    },
    {
      name: 'Sludge Bomb',
      cost: 2,
      cast: 3,
      coolDown: 7,
      powerRatio: 1,
      type: 'damage',
      singleTarget: true,
      onCooldown: false,
      description: "Damage the Boss's target for 100% Boss Power, Poison the Target dealing 60% of their Max Health over 15 seconds",
      icon: 'ra-poison-cloud'
    }
  ]
}
