export default {
  name: 'Seeping Slime',
  level: 2,
  initHp: 1000,
  hp: 1000,
  initPower: 40,
  power: 40,
  initArmor: 500,
  armor: 500,
  mana: 0,
  maxMana: 30,
  manaRegen: 1,
  armorRegen: 0,
  isCasting: false,
  bossTarget: null,
  description: "As you investigate the off coloured swamp water at the entrance of the swamp, the water starts investigating you.",
  weaponRewards: ['Plagued Aegis', 'Plagued Daggers', 'Plagued Wand', 'Plagued Sword', 'Plagued Stave', 'Plagued Scythe', 'Glowing Libram', 'Plagued Staff of the Swamp'],
  goldReward: 400,
  weaponChance: 1,
  progress_required: 0,
  spells: [
    {
      name: 'Regenerate',
      cast: 10,
      cost: 20,
      coolDown: 20,
      type: 'damage',
      singleTarget: false,
      powerRatio: 1,
      armor: 0,
      health: 500,
      onCooldown: false,
      description: 'Restore 500 Health. (Only usable when below 500 Health)',
    },
    {
      name: 'Seep',
      cast: 5,
      cost: 5,
      coolDown: 5,
      type: 'damage',
      singleTarget: true,
      powerRatio: 1,
      onCooldown: false,
      description: 'Damage All enemy characters for 100% Boss Power. This spell also damages the caster for 100% Power'
    },
    {
      name: 'Poison',
      cost: 0,
      cast: 2,
      coolDown: 5,
      powerRatio: 1,
      type: 'damage',
      singleTarget: true,
      onCooldown: false,
      description: "Apply a Poison Effect to the Boss' Target, Dealing 100% Boss Power as Damage every 5 seconds for 15 seconds"
    }
  ]
}
