export default {
  name: 'Collapsing Core',
  level: 3,
  initHp: 5000,
  hp: 5000,
  initPower: 30,
  power: 30,
  initArmor: 0,
  armor: 0,
  mana: 0,
  maxMana: 200,
  manaRegen: 0,
  armorRegen: 0,
  isCasting: false,
  bossTarget: null,
  description: `At the heart of the Volcano lives a Molten, Magnetic Core. The Core's Power was being funnelled out to the Conveyer and the Furnace, and it looks like the energy is being used for further devious means.`,
  weaponRewards: ['Polarizing Stick', 'Lightning Rod', 'Power Drill'],
  goldReward: 2000,
  weaponChance: 1,
  progress_required: 0,
  icon: ' ra-recycle',
  stage: 'stageZero',
  spells: [
    {
      name: 'Charge',
      cost: 0,
      cast: 10,
      coolDown: 0,
      powerRatio: 1,
      type: 'damage',
      singleTarget: false,
      onCooldown: false,
      stage: 'stageTwo'
      description: "(Only used when below 4000 Health) Change to Stage 2, gaining 25 Power",
      icon: 'ra-lever'
    },
    {
      name: 'Magma Surge',
      cost: 0,
      cast: 3,
      coolDown: 15,
      powerRatio: 1,
      percentage: 0.5,
      tickPower: 0,
      type: 'damage',
      singleTarget: false,
      isChanneled: true,
      ticks: 3,
      tickPercentage: 0.1,
      tickPower: 1,
      onCooldown: false,
      description: "Damage ALL Recruits for 30% of their Max Health during the cast, and then Damage the Target for (100%) Boss Power",
      icon: 'ra-lever'
    },
    {
      name: 'Magnetic Pulse',
      cost: 0,
      cast: 3,
      coolDown: 15,
      powerRatio: 1,
      percentage: 0.5,
      tickPower: 0,
      type: 'damage',
      singleTarget: false,
      isChanneled: true,
      ticks: 3,
      tickPower: 1,
      armor: 50,
      onCooldown: false,
      description: "Gain 150 Armor during the cast, and damage the target for (300%) PLAYER Power over the cast",
      icon: 'ra-lever'
    },
    {
      name: ''
    }
  ],
  stageTwo: {
    stage: 'stageTwo',
    description: 'During Stage 2 the Core will have 50 Power and gain 1 Mana per Second',
    manaRegen: 1,
    power: 50,
    spells: [
      {
        name: 'Meltdown',
        manaRequired: 100,
        cast: 10,
        cost: 0,
        coolDown: 0,
        onCooldown: false,
        singleTarget: false,
        powerRatio: 1,
        stage: 'stageOne',
        description: '(Only useable at 200 Mana) Change to Stage 3, gaining 50 Power and Poisoning ALL Recruits for (60%) of their Max Health over 15 seconds',
        icon: 'ra-gears'
      },
      // {
      //   name: 'Power Drill',
      //   cast: 5,
      //   cost: 0,
      //   coolDown: 1000,
      //   type: 'damage',
      //   powerRatio: 1,
      //   tickPower: 0.3,
      //   ticks: 5,
      //   isChanneled: true,
      //   onCooldown: false,
      //   singleTarget: true,
      //   description: "Damage the Boss' Target for (150%) Power during the cast",
      //   icon: 'ra-drill'
      // },
      {
        name: 'Radiation',
        cast: 5,
        cost: 0,
        coolDown: 10,
        type: 'damage',
        powerRatio: 1,
        onCooldown: false,
        singleTarget: true,
        description: "Damage ALL recruits for 40% of their Max Health during the cast and Poison them for (60%) of their Max Health over 15 seconds.",
        icon: 'ra-robot-arm'
      },
      // {
      //   name: 'Power Up',
      //   cast: 5,
      //   cost: 0,
      //   coolDown: 1000,
      //   type: 'damage',
      //   singleTarget: false,
      //   powerRatio: 50,
      //   power: 10,
      //   onCooldown: false,
      //   description: 'Gain 20 Power',
      //   icon: 'ra-heartburn'
      // }
    ]
  },
  stageThree: {
    stage: 'stageThree',
    description: 'During Stage 3 the Core will lose 1 Mana per second, increasing in Damage as the Mana reduces. Once at 0 Mana the Core will explode, killing the Player and their Recruits',
    manaRegen: -1,
    power: 100,
    spells: [
      {
        name: 'Repair',
        cast: 10,
        cost: 10,
        coolDown: 20,
        type: 'support',
        powerRatio: 1,
        power: 20,
        mana: 20,
        armor: 200,
        isChanneled: true,
        ticks: 10,
        onCooldown: false,
        singleTarget: false,
        description: "The Boss gains 20 Power, 20 Mana and restores 200 Armor during the cast of this spell",
        icon: 'ra-repair'
      },
      {
        name: 'Discharge',
        cast: 5,
        cost: 10,
        coolDown: 20,
        type: 'damage',
        isChanneled: true,
        singleTarget: false,
        onCooldown: false,
        tickPower: 0.1,
        powerRatio: 1,
        ticks: 10,
        tickPercentage: 0.05,
        description: 'Damage ALL recruits for 50% of their Max Health over the cast',
        icon: 'ra-defibrilate'
      },
      {
        name: 'Power Drill',
        cast: 5,
        cost: 0,
        coolDown: 20,
        type: 'damage',
        powerRatio: 1,
        tickPower: 0.3,
        ticks: 5,
        isChanneled: true,
        onCooldown: false,
        singleTarget: true,
        description: "Damage the Boss' Target for (150%) Power over the cast",
        icon: 'ra-drill'
      },
      {
        name: 'Speed Up',
        cast: 5,
        cost: 20,
        coolDown: 20,
        powerRatio: 1,
        percentage: 0.1,
        onCooldown: false,
        singleTarget: false,
        description: 'Reduce the Cast Time and Cooldown of ALL Boss Spells by 10%',
        icon: 'ra-recycle'
      }
    ]
  }
}
