export default {
  name: 'Flaming Furnace',
  level: 3,
  initHp: 2000,
  hp: 2000,
  initPower: 0,
  power: 0,
  initArmor: 2500,
  armor: 2500,
  mana: 0,
  maxMana: 1000,
  manaRegen: 0,
  armorRegen: 0,
  isCasting: false,
  bossTarget: null,
  description: "",
  weaponRewards: ['Curved Chassis', 'Afterburn Arrows', 'Cracked Chassis'],
  goldReward: 1500,
  weaponChance: 1,
  progress_required: 0,
  icon: 'ra-lava',
  spells: [
    {
      name: 'Unleash Flames',
      cost: 0,
      cast: 10,
      coolDown: 1,
      powerRatio: 0.3,
      tickPower: 0.5,
      type: 'damage',
      singleTarget: true,
      isChanneled: true,
      ticks: 10,
      onCooldown: false,
      description: "Useable when at 0 Armor: Damage ALL enemy recruits for (300%) Boss Power over the duration of the cast. Then change to Stage 2",
      icon: 'ra-fire-shield'
    },
    {
      name: 'Heat Up',
      cast: 5,
      cost: 0,
      coolDown: 20,
      type: 'damage',
      singleTarget: false,
      powerRatio: 50,
      power: 10,
      mana: 5,
      onCooldown: false,
      description: 'Gain 10 Power and 10 Mana during the cast, then damage ALL enemy characters for (100%) Boss Power',
      icon: 'ra-heartburn'
    },
    {
      name: 'Boil',
      cast: 5,
      cost: 0,
      coolDown: 0,
      type: 'damage',
      singleTarget: false,
      powerRatio: 1,
      ticks: 3,
      onCooldown: false,
      isChanneled: true,
      tickPower: 1,
      description: 'Damage a Random Enemy Recruit for 100% Boss Power 3 times over the duration of the cast',
      icon: 'ra-hot-surface'
    },
  ],
  stageTwo: {
    description: 'Enters Stage 2 after casting "Unleash Flames" at 0 Armor. During Stage 2 the Flaming Furnace will regenerate mana over time, and has a new set of spells.',
    manaRegen: 1,
    spells: [
      {
        name: 'Heat Up',
        cast: 5,
        cost: 0,
        coolDown: 10,
        type: 'damage',
        singleTarget: false,
        powerRatio: 50,
        power: 10,
        mana: 10,
        onCooldown: false,
        description: 'Gain 10 Power and 10 Mana',
        icon: 'ra-heartburn'
      },
      {
        name: 'Exhaust Heat',
        cast: 5,
        cost: 10,
        coolDown: 5,
        type: 'damage',
        singleTarget: false,
        powerRatio: 0.5,
        tickPower: 0.5,
        ticks: 5,
        onCooldown: false,
        isChanneled: true,
        power: -10,
        description: 'Damage ALL enemy Recruits for (50%) Boss Damage 5 times over the cast. Lose 10 Power',
        icon: 'ra-lava'
      },
      {
        name: 'Flame',
        cast: 3,
        cost: 5,
        coolDown: 0,
        type: 'damage',
        singleTarget: true,
        powerRatio: 0.5,
        power: 5,
        onCooldown: false,
        description: "Damage the Boss' Target and the Player for (100%) Boss Power. Lose 5 Power",
        icon: 'ra-burning-meteor'
      }
    ]
  }
}
