export default {
  name: 'Flaming Furnace',
  level: 3,
  initHp: 2000,
  hp: 2000,
  initPower: 0,
  power: 0,
  initArmor: 2000,
  armor: 0,
  mana: 0,
  maxMana: 1000,
  manaRegen: 0,
  armorRegen: 0,
  isCasting: false,
  bossTarget: null,
  description: "",
  weaponRewards: [],
  goldReward: 1500,
  weaponChance: 1,
  progress_required: 0,
  icon: 'ra-lava',
  spells: [
    {
      name: 'Unleash Flames',
      cost: 0,
      cast: 10,
      coolDown: 1,
      powerRatio: 0.5,
      tickPower: 0.5,
      type: 'damage',
      singleTarget: true,
      isChanneled: true,
      ticks: 5,
      onCooldown: false,
      description: "Useable when at 0 Armor: Damage ALL enemy recruits for (50%) Boss Power over the duration of the cast. Change to Stage 2",
      icon: 'ra-lava'
    },
    {
      name: 'Heat Up',
      cast: 5,
      cost: 0,
      coolDown: 10,
      type: 'damage',
      singleTarget: false,
      powerRatio: 50,
      power: 10,
      mana: 10,
      onCooldown: false,
      description: 'Gain 5 Power and 5 Mana',
      icon: 'ra-lava'
    },
    {
      name: 'Boil',
      cast: 10,
      cost: 0,
      coolDown: 5,
      type: 'damage',
      singleTarget: false,
      powerRatio: 1,
      ticks: 5,
      onCooldown: false,
      isChanneled: true,
      tickPower: 1,
      description: 'Damage a Random Enemy Recruit for 100% Boss Power 5 times over the duration of the cast',
      icon: 'ra-lava'
    },
  ],
  stageTwo: {
    description: 'Enters Stage 2 after casting "Unleash Flames" at 0 Armor',
    manaRegen: 1,
    spells: [
      {
        name: 'Heat Up',
        cast: 5,
        cost: 0,
        coolDown: 10,
        type: 'damage',
        singleTarget: false,
        powerRatio: 50,
        power: 10,
        mana: 10,
        onCooldown: false,
        description: 'Gain 20 Power and 20 Mana',
        icon: 'ra-lava'
      },
      {
        name: 'Exhaust Heat',
        cast: 5,
        cost: 10,
        coolDown: 5,
        type: 'damage',
        singleTarget: false,
        powerRatio: 0.5,
        tickPower: 0.5,
        ticks: 5,
        onCooldown: false,
        isChanneled: true,
        power: -10,
        description: 'Damage ALL enemy Recruits for (50%) Boss Damage 5 times over the cast. Lose 10 Power',
        icon: 'ra-lava'
      },
      {
        name: 'Flame',
        cast: 3,
        cost: 5,
        coolDown: 0,
        type: 'damage',
        singleTarget: true,
        powerRatio: 0.5,
        onCooldown: false,
        description: "Damage the Boss' Target and the Player for (100%) Boss Power."
      }
    ]
  }
}
