export default {
  name: 'Damaged Dragon',
  level: 1,
  initHp: 10000,
  hp: 3000,
  initPower: 1000,
  power: 0,
  initArmor: 5000,
  armor: 0,
  mana: 10,
  maxMana: 1000,
  manaRegen: 1,
  armorRegen: 0,
  isCasting: false,
  bossTarget: null,
  description: "A big scary Dragon, with a big Boo-Boo",
  weaponRewards: ['Dragon Scale'],
  goldReward: 500,
  weaponChance: 1,
  progress_required: 0,
  spells: [
    {
      name: 'Roar',
      cast: 1,
      cost: 10,
      coolDown: 20,
      type: 'damage',
      singleTarget: false,
      powerRatio: 100,
      onCooldown: false,
      description: 'Gain 100 Power',
    },
    {
      name: 'Feeble Fire',
      cast: 3,
      cost: 3,
      coolDown: 10,
      type: 'damage',
      singleTarget: false,
      powerRatio: 0.20,
      onCooldown: false,
      description: 'Damage ALL enemy characters for 20% BOSS POWER, lose 200 health',
    },
    {
      name: 'Weakened Bite',
      cost: 0,
      cast: 2,
      coolDown: 1,
      powerRatio: 0.1,
      type: 'damage',
      singleTarget: true,
      onCooldown: false,
      description: "Damage the TARGET for 10% of BOSS POWER, lose 100 health"
    }
  ]
}
