export default {
  name: 'Damaged Dragon',
  level: 1,
  initHp: 1000,
  hp: 200,
  initPower: 50,
  power: 30,
  initArmor: 500,
  armor: 0,
  mana: 0,
  maxMana: 1000,
  manaRegen: 1,
  armorRegen: 0,
  isCasting: false,
  bossTarget: null,
  description: "A big scary Dragon, with a big Boo-Boo",
  weaponRewards: ['Dragon Scale'],
  goldReward: 500,
  weaponChance: 1,
  progress_required: 0,
  spells: [
    {
      name: 'Roar',
      cast: 1,
      cost: 10,
      coolDown: 20,
      type: 'damage',
      singleTarget: false,
      powerRatio: 10,
      onCooldown: false,
      description: 'Gain 10 Power',
    },
    {
      name: 'Feeble Fire',
      cast: 5,
      cost: 3,
      coolDown: 10,
      type: 'damage',
      singleTarget: false,
      powerRatio: 0.10,
      onCooldown: false,
      description: 'Damage ALL enemy characters for 10% BOSS POWER, lose 20 health',
    },
    {
      name: 'Weakened Bite',
      cost: 0,
      cast: 5,
      coolDown: 1,
      powerRatio: 0.1,
      type: 'damage',
      singleTarget: true,
      onCooldown: false,
      description: "Damage the TARGET for 10% of BOSS POWER, lose 10 health"
    }
  ]
}
